### ISSUE TITLE
Category Variable Issue

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/acepack#1]
Nancy Kiang has requested some help with the following issue:

> I am trying my luck with ace with categorical variables or factors.  I cannot quite figure out the syntax for the 'cat' parameter description.  Could you please clarify?  
> 
> I've tested on some dummy variables, and here is what I'm getting:

```
#Test1, with a logical vector included, but not factor
x = 1:50
y=(1:50 - 25)^2  #Just a parabola
a= x<25  #Should pick out different halves of the parabola.
dat = data.frame(x=x , a=a)
junk = ace(x=dat, y=y)  #Okay! ACE converts a to 0's and 1'
plot(x, junk$ty)
plot(a, junk$ty)
plot(x, junk$tx[,'x'])
plot(a, junk$tx[,'a'])

#Test2, replace a with b, a factor vector, but do not use 'cat' parameter.
b = as.factor(a)
dat = data.frame(x=x, b=b)

junk = ace(x=dat, y=y)
## This is what I get:
Error in ace(x = dat, y = y) : 
  NA/NaN/Inf in foreign function call (arg 3)
In addition: Warning messages:
1: In mde(x) : NAs introduced by coercion
2: In mde(x) : NAs introduced by coercion

#Test 3, add a 'cat' parameter specifying cat=2, for 2nd column of x containing b
junk = ace(x=dat, y=y, cat=2)
Error in ace(x = dat, y = y, cat = 2) : 
  NA/NaN/Inf in foreign function call (arg 3)
In addition: Warning messages:
1: In mde(x) : NAs introduced by coercion
2: In mde(x) : NAs introduced by coercion
```

> I cannot find any examples of anyone using ace from acepack with categorical variables.  Does this feature work?  Is there some other syntax for 'cat'? Maybe it's better to rename it something else so that it can't get confused with the cat function in R?

**Comment by jonbaron1944** [comment]
I don't know why I am getting this. I do not have anything to do with
acepack anymore. I don't have time to try to figure this out.

On 04/23/19 21:01, Shawn Garbett wrote:
> Nancy Kiang has requested some help with the following issue:
> 
> > I am trying my luck with ace with categorical variables or factors.  I cannot quite figure out the syntax for the 'cat' parameter description.  Could you please clarify?  
> > 
> > I've tested on some dummy variables, and here is what I'm getting:
> 
> ```
> #Test1, with a logical vector included, but not factor
> x = 1:50
> y=(1:50 - 25)^2  #Just a parabola
> a= x<25  #Should pick out different halves of the parabola.
> dat = data.frame(x=x , a=a)
> junk = ace(x=dat, y=y)  #Okay! ACE converts a to 0's and 1'
> plot(x, junk$ty)
> plot(a, junk$ty)
> plot(x, junk$tx[,'x'])
> plot(a, junk$tx[,'a'])
> 
> #Test2, replace a with b, a factor vector, but do not use 'cat' parameter.
> b = as.factor(a)
> dat = data.frame(x=x, b=b)
> 
> junk = ace(x=dat, y=y)
> ## This is what I get:
> Error in ace(x = dat, y = y) : 
>   NA/NaN/Inf in foreign function call (arg 3)
> In addition: Warning messages:
> 1: In mde(x) : NAs introduced by coercion
> 2: In mde(x) : NAs introduced by coercion
> 
> #Test 3, add a 'cat' parameter specifying cat=2, for 2nd column of x containing b
> junk = ace(x=dat, y=y, cat=2)
> Error in ace(x = dat, y = y, cat = 2) : 
>   NA/NaN/Inf in foreign function call (arg 3)
> In addition: Warning messages:
> 1: In mde(x) : NAs introduced by coercion
> 2: In mde(x) : NAs introduced by coercion
> ```
> 
> > I cannot find any examples of anyone using ace from acepack with categorical variables.  Does this feature work?  Is there some other syntax for 'cat'? Maybe it's better to rename it something else so that it can't get confused with the cat function in R?
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/vubiostat/acepack/issues/1

-- 
Jonathan Baron, Professor of Psychology, University of Pennsylvania
Home page: https://www.sas.upenn.edu/~baron
Editor: Judgment and Decision Making (http://journal.sjdm.org)

**Comment by spgarbet** [comment]
The x variable is specified to be a numeric matrix. When you pass in a data.frame the data type is coerced properly in the first example. However, if anything in the data.frame is a factor it ends up coercing the entire matrix into characters which then crash out of acepack. This will make it work:

```
dat$b <- as.numeric(dat$b)
junk = ace(x=dat, y=y, cat=2)
plot(junk$ty)
```

**Comment by spgarbet** [comment]
@jonbaron1944 Since you were one of the owners at some point it's defaulting you to getting messages. On the main page of the acepack I think there's an unsubscribe button somewhere.

**Comment by spgarbet** [comment]
Eh, it looks like it's an issue by issue basis. I can remove you as an admin if you'd like. (and I'll just as gladly add you back if requested).

**Comment by nkianggiss** [comment]
Thanks, Shawn!   That solved it!  (Please add to the R help page for ace!)

**Comment by jonbaron1944** [comment]
Thanks. Yes. Please remove me.

On 04/23/19 14:11, Shawn Garbett wrote:
> Eh, it looks like it's an issue by issue basis. I can remove you as an admin if you'd like. (and I'll just as gladly add you back if requested).
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/vubiostat/acepack/issues/1#issuecomment-485976286

-- 
Jonathan Baron, Professor of Psychology, University of Pennsylvania
Home page: https://www.sas.upenn.edu/~baron
Editor: Judgment and Decision Making (http://journal.sjdm.org)
